//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherService.WeatherData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.gismeteo.ru/", ConfigurationName="WeatherData.WeatherSoap")]
    public interface WeatherSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetHHObservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WeatherService.WeatherData.HHObservationResult GetHHObservation(string serial, int location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetHHObservation", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherService.WeatherData.HHObservationResult> GetHHObservationAsync(string serial, int location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetHHForecast", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WeatherService.WeatherData.HHForecastResult GetHHForecast(string serial, int location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetHHForecast", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherService.WeatherData.HHForecastResult> GetHHForecastAsync(string serial, int location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetLocalTimeOffset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WeatherService.WeatherData.GetLocalTimeOffsetResult GetLocalTimeOffset(string serial, int location, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetLocalTimeOffset", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherService.WeatherData.GetLocalTimeOffsetResult> GetLocalTimeOffsetAsync(string serial, int location, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetGeoMagneticForecast", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WeatherService.WeatherData.GeoMagneticForecastResult GetGeoMagneticForecast(string serial, int location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetGeoMagneticForecast", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherService.WeatherData.GeoMagneticForecastResult> GetGeoMagneticForecastAsync(string serial, int location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetMoonInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WeatherService.WeatherData.GetMoonInfoResult GetMoonInfo(string serial, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetMoonInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherService.WeatherData.GetMoonInfoResult> GetMoonInfoAsync(string serial, System.DateTime dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetSunInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WeatherService.WeatherData.GetSunInfoResult GetSunInfo(string serial, int townID, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetSunInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherService.WeatherData.GetSunInfoResult> GetSunInfoAsync(string serial, int townID, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetMMForecast", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WeatherService.WeatherData.MMForecastResult GetMMForecast(string serial, int location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetMMForecast", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherService.WeatherData.MMForecastResult> GetMMForecastAsync(string serial, int location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetMMObservation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WeatherService.WeatherData.MMObservationResult GetMMObservation(string serial, int location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.gismeteo.ru/GetMMObservation", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherService.WeatherData.MMObservationResult> GetMMObservationAsync(string serial, int location);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class HHObservationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceResult resultField;
        
        private HHObservation dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public HHObservation data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class ServiceResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorCode errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ErrorCode errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public enum ErrorCode {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        BadSerial,
        
        /// <remarks/>
        WrongInputData,
        
        /// <remarks/>
        WrongLanguageProvided,
        
        /// <remarks/>
        DataNotFound,
        
        /// <remarks/>
        InternalError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class MMObservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime obsTimeField;
        
        private double tField;
        
        private double pField;
        
        private int clField;
        
        private double ddField;
        
        private double ffField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime obsTime {
            get {
                return this.obsTimeField;
            }
            set {
                this.obsTimeField = value;
                this.RaisePropertyChanged("obsTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double t {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
                this.RaisePropertyChanged("t");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double p {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
                this.RaisePropertyChanged("p");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int cl {
            get {
                return this.clField;
            }
            set {
                this.clField = value;
                this.RaisePropertyChanged("cl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double dd {
            get {
                return this.ddField;
            }
            set {
                this.ddField = value;
                this.RaisePropertyChanged("dd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double ff {
            get {
                return this.ffField;
            }
            set {
                this.ffField = value;
                this.RaisePropertyChanged("ff");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class MMObservationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceResult resultField;
        
        private MMObservation dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MMObservation data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class MMForecast : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime timeField;
        
        private int todField;
        
        private double tField;
        
        private double pField;
        
        private int clField;
        
        private double prcField;
        
        private int prctField;
        
        private double ddField;
        
        private double ffField;
        
        private int geomagneticField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int tod {
            get {
                return this.todField;
            }
            set {
                this.todField = value;
                this.RaisePropertyChanged("tod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double t {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
                this.RaisePropertyChanged("t");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double p {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
                this.RaisePropertyChanged("p");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int cl {
            get {
                return this.clField;
            }
            set {
                this.clField = value;
                this.RaisePropertyChanged("cl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double prc {
            get {
                return this.prcField;
            }
            set {
                this.prcField = value;
                this.RaisePropertyChanged("prc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int prct {
            get {
                return this.prctField;
            }
            set {
                this.prctField = value;
                this.RaisePropertyChanged("prct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double dd {
            get {
                return this.ddField;
            }
            set {
                this.ddField = value;
                this.RaisePropertyChanged("dd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double ff {
            get {
                return this.ffField;
            }
            set {
                this.ffField = value;
                this.RaisePropertyChanged("ff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int geomagnetic {
            get {
                return this.geomagneticField;
            }
            set {
                this.geomagneticField = value;
                this.RaisePropertyChanged("geomagnetic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class MMForecastResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceResult resultField;
        
        private MMForecast[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public MMForecast[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class GetSunInfoResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dtField;
        
        private int riseMinutesOffsetField;
        
        private int setMinutesOffsetField;
        
        private int durationMinutesField;
        
        private ServiceResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
                this.RaisePropertyChanged("dt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int riseMinutesOffset {
            get {
                return this.riseMinutesOffsetField;
            }
            set {
                this.riseMinutesOffsetField = value;
                this.RaisePropertyChanged("riseMinutesOffset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int setMinutesOffset {
            get {
                return this.setMinutesOffsetField;
            }
            set {
                this.setMinutesOffsetField = value;
                this.RaisePropertyChanged("setMinutesOffset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int durationMinutes {
            get {
                return this.durationMinutesField;
            }
            set {
                this.durationMinutesField = value;
                this.RaisePropertyChanged("durationMinutes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ServiceResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class GetMoonInfoResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float moonPhaseField;
        
        private bool waxField;
        
        private ServiceResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float moonPhase {
            get {
                return this.moonPhaseField;
            }
            set {
                this.moonPhaseField = value;
                this.RaisePropertyChanged("moonPhase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool wax {
            get {
                return this.waxField;
            }
            set {
                this.waxField = value;
                this.RaisePropertyChanged("wax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ServiceResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class GeoMagneticForecast : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dtField;
        
        private int gradeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
                this.RaisePropertyChanged("dt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
                this.RaisePropertyChanged("grade");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class GeoMagneticForecastResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceResult resultField;
        
        private GeoMagneticForecast[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GeoMagneticForecast[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class GetLocalTimeOffsetResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int offsetField;
        
        private ServiceResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("offset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ServiceResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class HHForecast : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime timeField;
        
        private int todField;
        
        private double tField;
        
        private double pField;
        
        private int clField;
        
        private double prcField;
        
        private int prctField;
        
        private double ddField;
        
        private double ffField;
        
        private int stField;
        
        private short humidityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int tod {
            get {
                return this.todField;
            }
            set {
                this.todField = value;
                this.RaisePropertyChanged("tod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double t {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
                this.RaisePropertyChanged("t");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double p {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
                this.RaisePropertyChanged("p");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int cl {
            get {
                return this.clField;
            }
            set {
                this.clField = value;
                this.RaisePropertyChanged("cl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double prc {
            get {
                return this.prcField;
            }
            set {
                this.prcField = value;
                this.RaisePropertyChanged("prc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int prct {
            get {
                return this.prctField;
            }
            set {
                this.prctField = value;
                this.RaisePropertyChanged("prct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double dd {
            get {
                return this.ddField;
            }
            set {
                this.ddField = value;
                this.RaisePropertyChanged("dd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double ff {
            get {
                return this.ffField;
            }
            set {
                this.ffField = value;
                this.RaisePropertyChanged("ff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int st {
            get {
                return this.stField;
            }
            set {
                this.stField = value;
                this.RaisePropertyChanged("st");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public short humidity {
            get {
                return this.humidityField;
            }
            set {
                this.humidityField = value;
                this.RaisePropertyChanged("humidity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class HHForecastResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceResult resultField;
        
        private HHForecast[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceResult result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HHForecast[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.gismeteo.ru/")]
    public partial class HHObservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime obsTimeField;
        
        private int todField;
        
        private double tField;
        
        private double pField;
        
        private int clField;
        
        private System.Nullable<double> humidityField;
        
        private double ddField;
        
        private double ffField;
        
        private int phField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime obsTime {
            get {
                return this.obsTimeField;
            }
            set {
                this.obsTimeField = value;
                this.RaisePropertyChanged("obsTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int tod {
            get {
                return this.todField;
            }
            set {
                this.todField = value;
                this.RaisePropertyChanged("tod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double t {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
                this.RaisePropertyChanged("t");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double p {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
                this.RaisePropertyChanged("p");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int cl {
            get {
                return this.clField;
            }
            set {
                this.clField = value;
                this.RaisePropertyChanged("cl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<double> humidity {
            get {
                return this.humidityField;
            }
            set {
                this.humidityField = value;
                this.RaisePropertyChanged("humidity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double dd {
            get {
                return this.ddField;
            }
            set {
                this.ddField = value;
                this.RaisePropertyChanged("dd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double ff {
            get {
                return this.ffField;
            }
            set {
                this.ffField = value;
                this.RaisePropertyChanged("ff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ph {
            get {
                return this.phField;
            }
            set {
                this.phField = value;
                this.RaisePropertyChanged("ph");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherSoapChannel : WeatherService.WeatherData.WeatherSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherSoapClient : System.ServiceModel.ClientBase<WeatherService.WeatherData.WeatherSoap>, WeatherService.WeatherData.WeatherSoap {
        
        public WeatherSoapClient() {
        }
        
        public WeatherSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WeatherService.WeatherData.HHObservationResult GetHHObservation(string serial, int location) {
            return base.Channel.GetHHObservation(serial, location);
        }
        
        public System.Threading.Tasks.Task<WeatherService.WeatherData.HHObservationResult> GetHHObservationAsync(string serial, int location) {
            return base.Channel.GetHHObservationAsync(serial, location);
        }
        
        public WeatherService.WeatherData.HHForecastResult GetHHForecast(string serial, int location) {
            return base.Channel.GetHHForecast(serial, location);
        }
        
        public System.Threading.Tasks.Task<WeatherService.WeatherData.HHForecastResult> GetHHForecastAsync(string serial, int location) {
            return base.Channel.GetHHForecastAsync(serial, location);
        }
        
        public WeatherService.WeatherData.GetLocalTimeOffsetResult GetLocalTimeOffset(string serial, int location, System.DateTime dt) {
            return base.Channel.GetLocalTimeOffset(serial, location, dt);
        }
        
        public System.Threading.Tasks.Task<WeatherService.WeatherData.GetLocalTimeOffsetResult> GetLocalTimeOffsetAsync(string serial, int location, System.DateTime dt) {
            return base.Channel.GetLocalTimeOffsetAsync(serial, location, dt);
        }
        
        public WeatherService.WeatherData.GeoMagneticForecastResult GetGeoMagneticForecast(string serial, int location) {
            return base.Channel.GetGeoMagneticForecast(serial, location);
        }
        
        public System.Threading.Tasks.Task<WeatherService.WeatherData.GeoMagneticForecastResult> GetGeoMagneticForecastAsync(string serial, int location) {
            return base.Channel.GetGeoMagneticForecastAsync(serial, location);
        }
        
        public WeatherService.WeatherData.GetMoonInfoResult GetMoonInfo(string serial, System.DateTime dt) {
            return base.Channel.GetMoonInfo(serial, dt);
        }
        
        public System.Threading.Tasks.Task<WeatherService.WeatherData.GetMoonInfoResult> GetMoonInfoAsync(string serial, System.DateTime dt) {
            return base.Channel.GetMoonInfoAsync(serial, dt);
        }
        
        public WeatherService.WeatherData.GetSunInfoResult GetSunInfo(string serial, int townID, System.DateTime date) {
            return base.Channel.GetSunInfo(serial, townID, date);
        }
        
        public System.Threading.Tasks.Task<WeatherService.WeatherData.GetSunInfoResult> GetSunInfoAsync(string serial, int townID, System.DateTime date) {
            return base.Channel.GetSunInfoAsync(serial, townID, date);
        }
        
        public WeatherService.WeatherData.MMForecastResult GetMMForecast(string serial, int location) {
            return base.Channel.GetMMForecast(serial, location);
        }
        
        public System.Threading.Tasks.Task<WeatherService.WeatherData.MMForecastResult> GetMMForecastAsync(string serial, int location) {
            return base.Channel.GetMMForecastAsync(serial, location);
        }
        
        public WeatherService.WeatherData.MMObservationResult GetMMObservation(string serial, int location) {
            return base.Channel.GetMMObservation(serial, location);
        }
        
        public System.Threading.Tasks.Task<WeatherService.WeatherData.MMObservationResult> GetMMObservationAsync(string serial, int location) {
            return base.Channel.GetMMObservationAsync(serial, location);
        }
    }
}
